# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba959a66a559884ad033ce1bfc377afc9d0e6bed2422c4e17590fe9a4e3091486ea5dacc71a03f37e9f807a0164451cabd2e84ca104c658974ce7fdd72673c4

test:
  secret_key_base: 95b91e22362630400580ed37cd05edf7de8bb1860fa864ebabd047f466afc0ff25c3449b5037c1a1a549a551bcca98b42022843daaa7cc731e6988a28ddf510c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
